name: mason_bug
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  mason:
    git:
      url: https://github.com/felangel/mason
      path: packages/mason
